/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ticket_manager.view;

import com.mycompany.ticket_manager.controller.StaffController;
import com.mycompany.ticket_manager.model.CurrentStaff;
import com.mycompany.ticket_manager.model.Login;
import com.mycompany.ticket_manager.model.Response;
import com.mycompany.ticket_manager.view.staff.readQr;
import com.mycompany.ticket_manager.view.admin.Main;
import com.mycompany.ticket_manager.view.staff.BuyTicket;

/**
 *
 * @author chien
 */
public class FrameLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrameLogin
     */
    StaffController staffController;

    public FrameLogin() {
        initComponents();
        this.setDefault();
        this.staffController = new StaffController();
    }

    private void setDefault() {
        this.email.setText("abc@gmail.com");
        this.password.setText("staff");
//        this.email.setText("chienboy03@gmail.com");
//        this.password.setText("admin");
        this.error.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        login_admin = new javax.swing.JButton();
        login_staff = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        login_staff1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setName("login"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Đăng nhập hệ thống");

        jLabel2.setText("Email");

        jLabel3.setText("Mật khẩu");

        login_admin.setText("Đăng nhập với admin");
        login_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickLoginAdmin(evt);
            }
        });

        login_staff.setText("Đăng nhập với nhân viên quầy");
        login_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickLoginStaffBuyTicket(evt);
            }
        });

        error.setForeground(new java.awt.Color(255, 51, 51));
        error.setText("err");

        login_staff1.setText("Đăng nhập với nhân viên soát ");
        login_staff1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_staff1clickLoginStaffBuyTicket(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(login_admin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(login_staff, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(login_staff1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email)))
                .addGap(107, 107, 107))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(3, 3, 3)
                .addComponent(error)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login_admin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login_staff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(login_staff1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setError(String error) {
        this.error.setText(error);
    }

    private void cleanError() {
        this.error.setText("");
    }

    private Login getInfoLogin() {
        String email = this.email.getText();
        String password = new String(this.password.getPassword());
        return new Login(email, password);
    }
    private void clickLoginAdmin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickLoginAdmin
        // TODO add your handling code here:
        Login infoLogin = this.getInfoLogin();
        Response response = this.staffController.login(infoLogin.getEmail(), infoLogin.getPassword(), "admin");
        if (response.getSuccess() == false) {
            this.error.setText(response.getMessage());
            return;
        }

        Main mainAdmin = new Main();
        mainAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_clickLoginAdmin

    private void clickLoginStaffBuyTicket(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickLoginStaffBuyTicket
        // TODO add your handling code here:
        Login infoLogin = this.getInfoLogin();
        Response<CurrentStaff> response = this.staffController.login(infoLogin.getEmail(), infoLogin.getPassword(), "staff");
        if (response.getSuccess() == false) {
            this.error.setText(response.getMessage());
            return;
        }

        BuyTicket mainBuy = new BuyTicket(response.getData());
        mainBuy.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_clickLoginStaffBuyTicket

    private void login_staff1clickLoginStaffBuyTicket(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_staff1clickLoginStaffBuyTicket
        // TODO add your handling code here:
        Login infoLogin = this.getInfoLogin();
        Response<CurrentStaff> response = this.staffController.login(infoLogin.getEmail(), infoLogin.getPassword(), "staff");
        if (response.getSuccess() == false) {
            this.error.setText(response.getMessage());
            return;
        }

        readQr readQr = new readQr(response.getData());
        readQr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_login_staff1clickLoginStaffBuyTicket

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton login_admin;
    private javax.swing.JButton login_staff;
    private javax.swing.JButton login_staff1;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
