/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.ticket_manager.view.admin;

import com.mycompany.ticket_manager.controller.MovieController;
import com.mycompany.ticket_manager.model.Movie;
import com.mycompany.ticket_manager.model.Response;
import com.mycompany.ticket_manager.model.Staff;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chien
 */
public class FrameInfoMovie extends javax.swing.JPanel {

    private List<Movie> listMovie;
    private MovieController movieController;

    /**
     * Creates new form FrameInfoMovie
     */
    public FrameInfoMovie() {
        initComponents();
        groupRadio.add(child);
        groupRadio.add(middle);
        groupRadio.add(old);
        groupRadio.add(nocheck);
        nocheck.setVisible(false);
        this.movieController = new MovieController();
        this.loadAllStaffToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupRadio = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        find_id = new javax.swing.JTextField();
        find_name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        nocheck = new javax.swing.JRadioButton();
        btn_edit = new javax.swing.JButton();
        btn_stop = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        price = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        middle = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        time = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        old = new javax.swing.JRadioButton();
        child = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        create = new javax.swing.JLabel();
        stop = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setText("Mã phim");

        jLabel2.setText("Tên phim");

        find_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                find_idActionPerformed(evt);
            }
        });

        find_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                find_nameActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jButton1.setText("Tìm kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickFindMovie(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jButton2.setText("Đang phát hành");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickFindMoviePlaying(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setText("Đã dừng");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickFindMovieStoped(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phim", "Tên phim", "Độ tuổi", "Giá vé", "Thời lượng", "Trạng thái"
            }
        ));
        table.setRowHeight(30);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickRowTable(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        nocheck.setText("nocheck");

        btn_edit.setBackground(new java.awt.Color(0, 204, 204));
        btn_edit.setText("Sửa");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickEdit(evt);
            }
        });

        btn_stop.setBackground(new java.awt.Color(255, 51, 51));
        btn_stop.setText("Dừng chiếu");
        btn_stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickStopMovie(evt);
            }
        });

        jLabel3.setText("Mã phim");

        jLabel4.setText("Tên phim");

        id.setEditable(false);

        jLabel6.setText("Giá thấp nhất(đ)");

        middle.setText("16+");

        jLabel5.setText("Độ tuổi");

        jLabel7.setText("Thời lượng(phút)");

        old.setText("18+");

        child.setText("Trẻ em");

        jLabel8.setText("Dừng chiếu");

        create.setText(" ");

        stop.setToolTipText("");
        stop.setEnabled(false);

        jLabel9.setText("Thời gian tạo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btn_edit)
                        .addGap(30, 30, 30)
                        .addComponent(btn_stop))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(35, 35, 35)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(27, 27, 27)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stop, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(child)
                                        .addGap(18, 18, 18)
                                        .addComponent(middle)
                                        .addGap(18, 18, 18)
                                        .addComponent(old))
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(nocheck, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(child)
                    .addComponent(middle)
                    .addComponent(old)
                    .addComponent(nocheck))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(stop))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(create))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_edit)
                    .addComponent(btn_stop))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(find_name, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                .addComponent(find_id))
                            .addGap(18, 18, 18)
                            .addComponent(jButton1))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(6, 6, 6)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(find_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(find_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void find_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_find_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_find_idActionPerformed

    private void find_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_find_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_find_nameActionPerformed

    private void clickStopMovie(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickStopMovie
        // TODO add your handling code here:
        if (this.id.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Id trống", "Thông báo lỗi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (this.stop.isSelected()) {
            JOptionPane.showMessageDialog(null, "Không thể dừng chiếu", "Thông báo lỗi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Response<List<Object>> response = this.movieController.stopMovie(this.id.getText());

        if (response.getSuccess() == false) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Thông báo lỗi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Movie movieInList = this.listMovie.get(table.getSelectedRow());
        movieInList.setHideAt((Long) response.getData().get(1));
        movieInList.setStrHideAt(response.getData().get(0).toString());
        this.stop.setSelected(true);
        this.stop.setText(movieInList.getStrHideAt());
        this.pushTable();
    }//GEN-LAST:event_clickStopMovie

    private void clickRowTable(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickRowTable
        // TODO add your handling code here:
        this.clean();
        int row = this.table.getSelectedRow();
        this.showInfoMovie(this.listMovie.get(row));

    }//GEN-LAST:event_clickRowTable

    private void clickEdit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickEdit
        // TODO add your handling code here:
        Movie movie = new Movie();
        movie.setId(this.id.getText());
        movie.setName(this.name.getText());
        movie.setAge(this.getAge());
        movie.setMinPrice((int) this.price.getValue());
        movie.setTime((int) this.time.getValue());

        Response<Movie> response = this.movieController.editMovie(movie);
        if (response.getSuccess() == false) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Thông báo lỗi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Movie movieInList = this.listMovie.get(table.getSelectedRow());
        movieInList.setName(response.getData().getName());
        movieInList.setAge(response.getData().getAge());
        movieInList.setMinPrice(response.getData().getMinPrice());
        movieInList.setTime(response.getData().getTime());
        this.pushTable();
        JOptionPane.showMessageDialog(null, "Cập nhật thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_clickEdit

    private void clickFindMovie(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickFindMovie
        // TODO add your handling code here:
        Response<List<Movie>> response = this.movieController.findMovie(this.find_id.getText(), this.find_name.getText());
        if (response.getSuccess() == false) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Thông báo lỗi", JOptionPane.WARNING_MESSAGE);
            return;
        }
        this.clean();
        this.listMovie = response.getData();
        this.pushTable();
    }//GEN-LAST:event_clickFindMovie

    private void clickFindMoviePlaying(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickFindMoviePlaying
        // TODO add your handling code here:
        this.ftMovie(true);
    }//GEN-LAST:event_clickFindMoviePlaying

    private void clickFindMovieStoped(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickFindMovieStoped
        // TODO add your handling code here:
        this.ftMovie(false);
    }//GEN-LAST:event_clickFindMovieStoped

    private void ftMovie(boolean playing) {
        Response<List<Movie>> response = this.movieController.findMovieStatus(playing);
        this.clean();
        this.listMovie = response.getData();
        this.pushTable();
    }

    private int getAge() {
        if (this.child.isSelected()) {
            return 1;
        } else if (this.middle.isSelected()) {
            return 16;
        } else if (this.old.isSelected()) {
            return 18;
        } else {
            return -1;
        }
    }

    private void loadAllStaffToTable() {
        Response<List<Movie>> response = this.movieController.getAllMovie();

        if (response.getSuccess() == false) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Thông báo lỗi", JOptionPane.WARNING_MESSAGE);
            return;
        }
        this.listMovie = response.getData();
        this.pushTable();
    }

    private void pushTable() {
        DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
        tableModel.setRowCount(0);
        for (Movie movie : this.listMovie) {
            Object[] data = {movie.getId(), movie.getName(), movie.getAge(), movie.getMinPrice(), movie.getTime(), movie.getHideAt() == 0 ? "Đang chiếu" : "Dừng chiếu"};
            tableModel.addRow(data);
        }
    }

    private void clean() {
        this.name.setText("");
        this.id.setText("");
        this.nocheck.setSelected(true);
        this.price.setValue(0);
        this.time.setValue(0);
        this.stop.setText("");
        this.stop.setSelected(false);
        this.create.setText("");
    }

    private void showInfoMovie(Movie movie) {
        this.id.setText(movie.getId());
        this.name.setText(movie.getName());
        this.setAge(movie.getAge());
        this.price.setValue(movie.getMinPrice());
        this.time.setValue(movie.getTime());
        if (movie.getHideAt() != 0) {
            this.stop.setSelected(true);
            this.stop.setText(movie.getStrHideAt());
        }
        this.create.setText(movie.getStrCreateAt());
    }

    private void setAge(int age) {
        switch (age) {
            case 1:
                this.child.setSelected(true);
                break;
            case 16:
                this.middle.setSelected(true);
                break;
            case 18:
                this.old.setSelected(true);
                break;
            default:
                this.nocheck.setSelected(true);
                break;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_stop;
    private javax.swing.JRadioButton child;
    private javax.swing.JLabel create;
    private javax.swing.JTextField find_id;
    private javax.swing.JTextField find_name;
    private javax.swing.ButtonGroup groupRadio;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton middle;
    private javax.swing.JTextField name;
    private javax.swing.JRadioButton nocheck;
    private javax.swing.JRadioButton old;
    private javax.swing.JSpinner price;
    private javax.swing.JCheckBox stop;
    private javax.swing.JTable table;
    private javax.swing.JSpinner time;
    // End of variables declaration//GEN-END:variables
}
